- app/views/include/fieldError.scala.html
- app/views/review/review.scala.html
- conf/application.conf
* Error validation.
* Addition of data attributes for JS to dynamically toggle GA event value based on radio button selection.
* Update of `assets-frontend` version to 2.207.0.
> [API-1355] API Gatekeeper Review Application Page

- app/connectors/DeveloperConnector.scala
- project/FrontendBuild.scala
- test/unit/connectors/DeveloperConnectorSpec.scala
Urlencoding enabled for the email based application searches.
> API-1633: Now urlencoding email addresses for application GET request

- app/views/review/review.scala.html
- test/acceptance/specs/APIGatekeeperReviewSpec.scala
See also API-1276 for further context
> APIS-554: Fix broken Naming Guidelines URL

- app/controllers/DevelopersController.scala
Issue occurred when selecting a new page size, but with no group selected
> API-604: Fix for the dropdown bug.

- app/model/Model.scala
- app/services/DeveloperService.scala
- test/unit/controllers/DevelopersControllerSpec.scala
- test/unit/services/DeveloperServiceSpec.scala
subscriptions removed from `ApplicationResponse` on third-party-application service, so same here
> API-610: Align application response object with same on third-party-application

- app/controllers/TabHelper.scala
- app/views/dashboard/dashboard.scala.html
- app/views/developers/developers.scala.html
- app/views/include/tabList.scala.html
- conf/application.conf
* Tab layout on dashboard page
* Consistent styling of verified/unverified links
> APIS-686: dashboard tabs

- app/views/developers/developers.scala.html
and change style to match prototype
> APIS-845 move the Previous button to be alongside the Next button

- conf/application.conf
> APIS-947 - Add Stub version of AUTH Service

- app/controllers/DevelopersController.scala
- app/model/Developers.scala
- app/services/ApplicationService.scala
- app/services/DeveloperService.scala
- test/unit/controllers/DevelopersControllerSpec.scala
- test/unit/model/DeveloperSpec.scala
- test/unit/services/ApplicationServiceSpec.scala
- test/unit/services/DeveloperServiceSpec.scala
* Moved FetchApplications and added a filter-free version
* Moved email list logic into Developers class
* Updated tests to reflect the changes
> Moved Application logic from DeveloperService to ApplicationService

- app/assets/javascripts/developers.js
- app/assets/stylesheets/main.scss
- app/assets/stylesheets/partials/developers.scss
- app/views/developers/developers.scala.html
- app/views/main.scala.html
- conf/app.routes
- project/MicroService.scala
- project/plugins.sbt
- test/acceptance/specs/APIGatekeeperDeveloperSpec.scala
For future maintainability, and production assets pipeline
@rm-hull
> Move inline scripts/styles to assets

- app/assets/javascripts/developers.js
- project/MicroService.scala
> Stop checking for unused variables

- app/views/applications/applications.scala.html
- project/MicroService.scala
- project/plugins.sbt
* Updated Scala to latest 2.11.x release
* Updated Play to latest 2.5.x release
> Application text search now ignores status field

- jenkins-start-with-assets-frontend.sh
- identical script to api-documentation-raml-frontend to run `test acceptance:test`
> Add private jenkins test script

- app/assets/javascripts/datatables.js
- app/views/applications/applications.scala.html
- while stopping input box filtering by status
- standardised datatable setup in html
> Restore filtering by status drop down box

- .travis.yml
> Updated travis.yml to run sandbox tests

- app/assets/stylesheets/partials/ad-hoc.scss
- app/config/ApplicationGlobal.scala
- app/config/FrontendWiring.scala
- conf/application.conf
Also:
* Added missing metrics configuration
* Aligned global to be similar to TPDFE
* Updated assets version
> APIS-1490: Missing auditing configuration exceptions reported

- app/views/developers/developers.scala.html
Changed order of the fields displayed to match the table
> APIS-971 change order of fields

- build.sbt
- test/acceptance/Env.scala
- test/acceptance/NavigationSugar.scala
- test/acceptance/WebPage.scala
Reverts hmrc/api-gatekeeper-frontend#144
> Revert "APIS-3219"

- app/views/applications/application.scala.html
- app/views/helper/application/package.scala
- test/unit/views/helper/application/ApplicationReviewSpec.scala
> APIS-3373 - removed check for approval before showing submission details

- app/assets/javascripts/copy-to-clip.js
- app/views/applications/application.scala.html
- app/views/developers/developers.scala.html
- app/views/helper/EmailsFormatter.scala
- test/acceptance/pages/ApplicationPage.scala
- test/acceptance/specs/APIGatekeeperApplicationSpec.scala
> APIS-3414 - Buttons to copy emails to clipboard on an application page

- app/views/applications/application.scala.html
- test/unit/view/applications/ApplicationViewSpec.scala
if status is still in "pending verification"
> APIS-3413 added missing link to resend an email 

- app/controllers/Developers2Controller.scala
- app/views/developers/developers2.scala.html
- test/unit/controllers/Developers2ControllerSpec.scala
- Added to new developers search page.
> APIS-4405 - Added a copy emails to clipboard button

- test/acceptance/specs/APIGatekeeperBaseSpec.scala
> APIS-4406 - Fixed some broken AT's for getting developers

- app/services/ApplicationService.scala
- test/unit/services/ApplicationServiceSpec.scala
APSR-1197 - Removed showing subscriptions in the application search page results as it was crashing in prod.
> APSR-1197 - Removed showing subscriptions in the app search results.

- app/connectors/SubscriptionFieldsConnector.scala
- app/model/Application.scala
- app/model/Model.scala
- app/model/SubscriptionFields.scala
- app/services/SubscriptionFieldsService.scala
- app/views/applications/ApplicationView.scala.html
- app/views/applications/CreateApplicationSuccessView.scala.html
- test/builder/SubscriptionsBuilder.scala
- test/connectors/ApplicationConnectorSpec.scala
- test/connectors/ProxiedHttpClientSpec.scala
- test/connectors/SubscriptionFieldsConnectorSpec.scala
- test/controllers/ApplicationControllerSpec.scala
- test/controllers/ControllerSetupBase.scala
- test/controllers/DevelopersControllerSpec.scala
- test/model/ModelSpec.scala
- test/model/SubscribedApplicationResponseSpec.scala
- test/services/ApplicationServiceSpec.scala
- test/services/DeveloperServiceSpec.scala
- test/services/SubscriptionFieldsServiceSpec.scala
- test/utils/ApplicationGenerator.scala
- test/views/applications/ApplicationViewSpec.scala
- test/views/applications/CreatePrivOrROPCAppSuccessViewSpec.scala
- test/views/applications/DeleteApplicationViewSpec.scala
- test/views/developers/DeleteDeveloperViewSpec.scala
- test/views/developers/DeveloperDetailsViewSpec.scala
Co-authored-by: Pete Slater <pslater@equalexperts.com>
> APIS-4825  - ClientId is a Value Class

- app/controllers/ApplicationController.scala
Co-authored-by: Pete Slater <pslater@equalexperts.com>
> APIS-4825 - Fix for Sub Configuration on App details page

- app/controllers/ApplicationController.scala
Co-authored-by: Pete Slater <pslater@equalexperts.com>
> APIS-4825 - Sort API Subs on App Details Page

- acceptance/acceptance/NavigationSugar.scala
- acceptance/acceptance/SignInSugar.scala
- acceptance/acceptance/WebPage.scala
- acceptance/acceptance/specs/ApiGatekeeperApplicationSpec.scala
- acceptance/acceptance/specs/ApiGatekeeperDeleteApplicationSpec.scala
- acceptance/acceptance/specs/ApiGatekeeperDeveloper2Spec.scala
- acceptance/acceptance/specs/ApiGatekeeperDeveloperDetailsSpec.scala
- acceptance/acceptance/specs/ApiGatekeeperDeveloperSpec.scala
- acceptance/acceptance/specs/ApiGatekeeperRemoveMfaSpec.scala
- app/controllers/ApplicationController.scala
- test/controllers/DevelopersControllerSpec.scala
- test/controllers/SubscriptionControllerSpec.scala
- test/services/ApplicationServiceSpec.scala
- test/services/DeploymentApprovalServiceSpec.scala
- test/services/DeveloperServiceSpec.scala
Fixing a broken test revealed acceptance tests that have been broken for some indeterminate period of time - the on(Page) method was faulty.
> APIS-5254 - Fix tests

- app/controllers/ApplicationController.scala
- app/model/Application.scala
- app/views/applications/ManageGrantLengthView.scala.html
…tLength is unexpected to convert int to enum
> APID-271 - 1. UI Tweaks to use legend, div 2. Throw exception if grantLength is unexpected to convert int to enum

- app/controllers/DeploymentApprovalController.scala
- test/controllers/DeploymentApprovalControllerSpec.scala
This is only for PRODUCTION apis.
> API-5188: Update API Gatekeeper (Approvals Journey) to publish to API Catalogue

- app/assets/stylesheets/partials/ad-hoc.scss
- app/controllers/ApplicationController.scala
- app/model/Application.scala
- app/utils/PaginationHelper.scala
- app/views/applications/ApplicationsView.scala.html
- app/views/include/pagination.scala.html
- conf/app.routes
- test/controllers/ApplicationControllerSpec.scala
- test/utils/PaginationHelperSpec.scala
Add hidden page to return applications search results in a CSV
> APIS-5542 - Hidden page to extract Applications as CSV

- app/views/applications/ApplicationsView.scala.html
> APIS-5542 - Add id to the apps search submit button

- app/connectors/SubscriptionFieldsConnector.scala
- app/controllers/ApiDefinitionController.scala
- app/controllers/ApplicationController.scala
- app/controllers/SubscriptionFieldsController.scala
- app/model/SubscriptionFields.scala
- app/services/SubscriptionFieldsService.scala
- app/utils/CsvHelper.scala
- conf/app.routes
- test/connectors/SubscriptionFieldsConnectorSpec.scala
- test/controllers/SubscriptionFieldsControllerSpec.scala
- test/services/SubscriptionFieldsServiceSpec.scala
- test/utils/CsvHelperHelperSpec.scala
- Add page to return subscription fields values (cliendId + name) 
- Extracted CsvHelper
- Refactored ApiDefinitionsController to use CsvHelper
> APIS-5723 - Add page to return all subscription fields values as CSV

- app/model/Application.scala
- app/model/applications/NewApplication.scala
- app/views/helper/application/package.scala
- test/connectors/ApplicationConnectorSpec.scala
- test/controllers/ApplicationControllerSpec.scala
- test/controllers/ControllerSetupBase.scala
- test/controllers/DevelopersControllerSpec.scala
- test/model/ModelSpec.scala
- test/model/applications/NewApplicationSpec.scala
- test/services/ApplicationServiceSpec.scala
- test/services/DeveloperServiceSpec.scala
- test/views/ApplicationsViewSpec.scala
- test/views/applications/ApplicationViewSpec.scala
- test/views/applications/DeleteApplicationViewSpec.scala
- test/views/applications/IpAllowlistViewSpec.scala
- testCommon/builder/ApplicationBuilder.scala
- testCommon/builder/ApplicationResponseBuilder.scala
thirrd-party-application model
> API-5338: Changed application lastAccess to be an option to match

- app/uk/gov/hmrc/gatekeeper/controllers/ApplicationController.scala
- app/uk/gov/hmrc/gatekeeper/views/applications/ManageGrantLengthSuccessView.scala.html
- app/uk/gov/hmrc/gatekeeper/views/helper/application/GrantLengthDisplayer.scala
- conf/logback.xml
- test/uk/gov/hmrc/gatekeeper/views/helper/application/GrantLengthDisplayerSpec.scala
> API-7667 - Update content on "Manage application grant length" page

- app/uk/gov/hmrc/gatekeeper/config/AppConfig.scala
- app/uk/gov/hmrc/gatekeeper/controllers/ApplicationController.scala
- conf/application.conf
> API-7664: remove conditional displaying of 4h grant length option

- app/uk/gov/hmrc/gatekeeper/controllers/DevelopersController.scala
- test/uk/gov/hmrc/gatekeeper/controllers/DevelopersControllerSpec.scala
Reverts hmrc/api-gatekeeper-frontend#660
> Revert "APIS-7362 Removed PII data from developers export CSV and added UserId"

- app/uk/gov/hmrc/gatekeeper/connectors/ThirdPartyOrchestratorConnector.scala
- app/uk/gov/hmrc/gatekeeper/controllers/OrganisationController.scala
- app/uk/gov/hmrc/gatekeeper/models/organisations/OrganisationWithApps.scala
- app/uk/gov/hmrc/gatekeeper/services/OrganisationService.scala
- app/uk/gov/hmrc/gatekeeper/views/applications/OrganisationView.scala.html
- test/uk/gov/hmrc/gatekeeper/connectors/ThirdPartyOrchestratorConnectorSpec.scala
- test/uk/gov/hmrc/gatekeeper/controllers/OrganisationControllerSpec.scala
- test/uk/gov/hmrc/gatekeeper/mocks/connectors/ThirdPartyOrchestratorConnectorMockProvider.scala
- test/uk/gov/hmrc/gatekeeper/mocks/services/OrganisationServiceMockProvider.scala
- test/uk/gov/hmrc/gatekeeper/services/OrganisationServiceSpec.scala
- test/uk/gov/hmrc/gatekeeper/views/OrganisationViewSpec.scala
Reverts hmrc/api-gatekeeper-frontend#665
> Revert "APIS-7302: Filter application by subscriptions"

- app/uk/gov/hmrc/gatekeeper/connectors/ApiPublisherConnector.scala
- app/uk/gov/hmrc/gatekeeper/controllers/ApiApprovalsController.scala
- app/uk/gov/hmrc/gatekeeper/services/DeploymentApprovalService.scala
- app/uk/gov/hmrc/gatekeeper/views/apiapprovals/ApiApprovalsCommentSuccessView.scala.html
- app/uk/gov/hmrc/gatekeeper/views/apiapprovals/ApiApprovalsCommentView.scala.html
- app/uk/gov/hmrc/gatekeeper/views/apiapprovals/ApiApprovalsHistoryView.scala.html
- conf/app.routes
- conf/messages
- test/uk/gov/hmrc/gatekeeper/connectors/ApiPublisherConnectorSpec.scala
- test/uk/gov/hmrc/gatekeeper/controllers/ApiApprovalsControllerSpec.scala
- test/uk/gov/hmrc/gatekeeper/mocks/connectors/ApiPublisherConnectorMockProvider.scala
- test/uk/gov/hmrc/gatekeeper/mocks/services/DeploymentApprovalServiceMockProvider.scala
- test/uk/gov/hmrc/gatekeeper/services/DeploymentApprovalServiceSpec.scala
Also includes:
APIS-7473: Add Comment Button
APIS-7478: API Comment Confirmation Message
> APIS-7477: Add Comment Dialogue Box
